version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: flexcrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    command:
      - "/usr/bin/supervisord"
      - "-c"
      - "/etc/supervisor/conf.d/supervisord.ini"
    restart: always
    volumes:
      - ./media:/app/backend/flexcrm/media
    depends_on:
      - db


  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 5173:5173
    command:
      - "serve"
      - "-s"
      - "dist"
