version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: flexcrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data/
    expose:
      - 5432
    networks:
      - backend-network

  nginx:
    image: nginx:1.27.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/usr/share/nginx/media
      - uwsgi_sock:/run
      - static:/usr/share/nginx/html
    command:
      - "nginx"
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    networks:
      - backend-network
      - frontend-network
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    networks:
      - backend-network
    expose:
      - 8000
    command:
      - "/usr/bin/supervisord"
      - "-c"
      - "/etc/supervisor/conf.d/supervisord.ini"
    restart: always
    volumes:
      - uwsgi_sock:/run
      - ./media:/app/backend/flexcrm/media
    depends_on:
      - db


  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - static:/app/frontend/dist
    networks:
      - frontend-network
    expose:
      - 5173

volumes:
  uwsgi_sock:
  static:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge