# Generated by Django 5.1.6 on 2025-03-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crmapp.add'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crmapp.lead'),
        ),
    ]
