# Generated by Django 5.1.6 on 2025-03-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_customer_adds_alter_customer_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='leads_count',
        ),
    ]
