# Generated by Django 5.1.6 on 2025-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='customers_count',
            field=models.IntegerField(default=0),
        ),
    ]
