# Generated by Django 5.1.6 on 2025-03-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_alter_add_customers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crmapp.product'),
        ),
    ]
