# Generated by Django 5.1.6 on 2025-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_alter_add_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='product',
        ),
        migrations.AddField(
            model_name='add',
            name='product',
            field=models.ManyToManyField(to='crmapp.product'),
        ),
    ]
