# Generated by Django 5.1.6 on 2025-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_remove_add_product_add_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='adds',
        ),
        migrations.AddField(
            model_name='customer',
            name='adds',
            field=models.ManyToManyField(to='crmapp.add'),
        ),
    ]
