# Generated by Django 5.1.6 on 2025-03-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_remove_customer_adds_customer_adds'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='crmapp.product'),
            preserve_default=False,
        ),
    ]
