# Generated by Django 5.1.6 on 2025-03-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_contract_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts', to='crmapp.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts', to='crmapp.product'),
        ),
    ]
