# Generated by Django 5.1.6 on 2025-03-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_customer_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Ad',
        ),
    ]
